### ISSUE TITLE
The projects in the reactor contain a cyclic reference

### ISSUE THREAD

**Issue by zhangqqqf** [lets-blade/blade#101]
Edge between 'Vertex{label='com.bladejava:blade-embed-jetty:0.1.3'}' and 'Vertex{label='com.bladejava:blade-core:1.7.2-beta'}' introduces to cycle in the graph com.bladejava:blade-core:1.7.2-beta --> com.bladejava:blade-embed-jetty:0.1.3 --> com.bladejava:blade-core:1.7.2-beta 

maven compile error!

**Comment by hellokaton** [comment]
hi @zhangqqqf ,you can try `2.0.1-beta2`, use Netty as network support in the new version.
