### ISSUE TITLE
Gradle projects can't access static resources

### ISSUE THREAD

**Issue by yuxino** [lets-blade/blade#102]
## Environment
| environment| version |
| ------- | -------- |
| Gradle | 3.5.0     |
| Maven | 3.5.0     |
| JDK     | 1.8.0_131|
| Window | 10 |

## Description
I wrote demo according to the [tutorial](https://biezhi.gitbooks.io/blade-in-action/content/chapter2/2.4-static-resource.html).The only difference is that I used Gradle to build Blade project.Then I ran into a problem that I couldn't access static resources. But when i using maven to build Blade project with same code , I could have access static resource .I don't know why.

## Screenshot of the problem
Following is the use of Gradle

![image](https://user-images.githubusercontent.com/12481935/27525849-e9ba1080-5a73-11e7-990b-7438e22e237a.png)

Access the resource

![image](https://user-images.githubusercontent.com/12481935/27525859-fc4ea7b0-5a73-11e7-8bce-7ab885d83c19.png)

Following is the use of Maven

![image](https://user-images.githubusercontent.com/12481935/27525864-022e9c1c-5a74-11e7-8020-ef0cdbe22de7.png)

Access the resource

![image](https://user-images.githubusercontent.com/12481935/27525871-115c33ac-5a74-11e7-9bc0-6f29beaabc4f.png)

## Config
The following is the configuration of Gradle

``` gradle
group 'nbsaw'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/com.bladejava/blade-mvc
    compile group: 'com.bladejava', name: 'blade-mvc', version: '2.0.0-beta'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

**Comment by hellokaton** [comment]
fixed https://github.com/lets-blade/blade/commit/ec8dc9ad73696ed7862fc045377bdff2a6d4c8d4
