### ISSUE TITLE
Blade.me().get("/",    (request, response) -> response.text("Hello World")).start() 报错

### ISSUE THREAD

**Issue by easonzhang1992** [lets-blade/blade#103]
您好：
  您的gitBook  1.2 章节中 运行Hello World示例代码：
  Blade.me().get("/",    (request, response) -> response.text("Hello World")).start();
请问下，request 和 response是从哪里得来的？我直接拷贝到本地会报错啊

**Comment by hellokaton** [comment]
hi @easonzhang1992 `Request` 和 `Response` 对象是框架自动注入进去的，当有请求进来的时候就会有，你本地报错是什么信息报错，可以告诉我你的项目结构/环境吗？

**Comment by CodeChenlei** [comment]
您好，我这边是fork的您在github上的blade的demo，blade-demos，然后直接clone到自己的git库里面，然后将之当作maven工程导入eclipse中，我本地的jdk版本为jdk1.8，启动Application的main方法，控制台会报“Exception in thread "main" java.lang.NoSuchMethodError: com.blade.Blade.of()Lcom/blade/Blade;”的错误。

**Comment by hellokaton** [comment]
这个是没有下载到jar包的原因，可以再试试呢。
