### ISSUE TITLE
好几个类显示log缺失

### ISSUE THREAD

**Issue by jetablezhu** [lets-blade/blade#105]
log.info("Environment: jdk.version\t\t=> {}", System.getProperty("java.version"));
类似这样的，log类都没有定义，是因为我缺少哪些引用么？

**Comment by jetablezhu** [comment]
了解了，原来用的是Lombok，忽略哈

**Comment by hellokaton** [comment]
@jetablezhu 为了简化代码我在源码中使用了 `lombok` 这个神器。
