### ISSUE TITLE
eclipse Errors: log cannot be resolved

### ISSUE THREAD

**Issue by zmendax** [lets-blade/blade#109]
eclipse 导入后，com.blade包和其他几个引用到log的类均报错，problems视图显示 log cannot be resolved. jdk 版本1.8。project->clean 无效， 应该如何解决？

**Comment by Glauy** [comment]
你好，解决了没有啊

**Comment by hellokaton** [comment]
嗨，因为源码中使用了 `lombok` 插件，你可以先了解然后安装一下。

**Comment by Glauy** [comment]
知道了
