### ISSUE TITLE
Blade.of 编译不通过

### ISSUE THREAD

**Issue by javen-73** [lets-blade/blade#112]

**Comment by javen-73** [comment]
没有这个方法

**Comment by hellokaton** [comment]
嗨，@javen-73 一些人反馈 `Blade.me()` 和 `Blade.of()` 方法重复了，所以去除了。可以关注最近在[youtube](https://www.youtube.com/watch?v=UQzz1XCFE9U&list=PLK2w-tGRdrj5TV2lxHFj8hcg4mbmRmnWX) 和 [腾讯视频](http://v.qq.com/vplus/56171fe5fc0541ba6f356522325b0902/foldervideos/w6g0008012ruo91) 发布的Blade教程，它们会让你更快上手。
