### ISSUE TITLE
怎么实现自定义注解

### ISSUE THREAD

**Issue by SpringStudent** [lets-blade/blade#123]

**Comment by hellokaton** [comment]
自定义注解的用途是？

**Comment by SpringStudent** [comment]
实现方法级别的权限控制

**Comment by hellokaton** [comment]
目前 `Blade` 没有内置AOP的实现。你的这个功能可以通过自定义注解的方式实现，`Blade` 有 `WebHook` 的机制（类似SpringMvc中的拦截器），在这里可以获取到路由的 `Method`，其他问题迎刃而解。

**Comment by SpringStudent** [comment]
我试着通过WebHook实现但是失败了
代码如下

![image](https://user-images.githubusercontent.com/14833956/31476589-aecc4bda-af39-11e7-9eec-e0050b0f71bb.png)


请问是我获取注解方式有问题吗

signature.getAction().getAnnotation(NeedLogin.class);这个方法貌似拿到的注解为WebHook的before方法上的注解

**Comment by hellokaton** [comment]
你的写法没问题，看样子这是一个 `bug`，我将升级一个版本修复它

**Comment by SpringStudent** [comment]
ok，谢谢你
