### ISSUE TITLE
和springmvc相比有什么比较 突出 的优点啊？底层通讯必须用netty？

### ISSUE THREAD

**Issue by ghost** [lets-blade/blade#143]

**Comment by hellokaton** [comment]
1. 即便是比较也是和SpringBoot而不是SpringMVC
2. 源码比Spring系列小
3. 性能比Spring系列高
4. 以JAR包为Web服务，不依赖Tomcat
5. 原生支持WebSocket
6. 学习成本更低

其他的特性可能会在未来出现，但MVC、Web框架的大体形式都是如此，不会有太大的不同之处。
Web服务是使用Netty搭建的，这不需要使用者实现。Blade 提供了一个 Spring 之外的选择，让开发者可以在没有Servlet规范下也明白Web服务是如何运作的。

**Comment by ghost** [comment]
get, thanks

**Comment by caoli5288** [comment]
不支持丢容器里运行不一定在所有时候都是优点，，

**Comment by dongm2ez** [comment]
@caoli5288  tomcat 是一个 servlet 容器，blade 不使用其说明根本没用到 servlet 容器提供的任何东西。抛开 tomcat 使得 blade 更灵活，容器有很多种，抛开 tomcat，blade 实际对 docker 这类容器更友好，放入 docker 中可以大大提供 blade 的高可用性。

部署的简单，让 blade 的 docker 容器构建更容易，一个机器里跑上百个 blade，通过 docker 编排可以非常容易做到。

java 发展了这么多年，java 信仰者认为 tomcat 这种 servlet 容器就是 java 开发必须的，甚至有的开发者都不明白 servlet 提供了什么 ，java 提供了什么，那么抛开 servlet 容器，没有 servlet 容器提供的功能，我们会发现开发java应用是一样的，并不是不可或缺的。抛开了束缚，我们获得和失去了什么，这才是需要思考的。

**Comment by caoli5288** [comment]
@dongm2ez blade并不适合docker，以netty的并发能力并没有单机多实例的必要，强行这样部署反而会引入竞争降低吞吐量，况且docker有其固有的劣势，容器间的网络流量在用户空间转发的网络模型严重限制了吞吐量上限，这几乎就是跟netty的设计目的根本冲突，我司大约在前年测试的结果是在10G网口上吞吐量几乎下降了70-100%（网络短暂崩溃）。

docker原生不支持有状态的“会话”，不支持容器内数据持久化，其网络模型也决定了不支持获取原始套接字，为了解决这些需要在docker前端引入额外的设施，增加额外的系统复杂度，这些都是blade场景可能需要面对的。

我用Servlet很少，针对其优缺点就不发表拙见了，但是你看看blade依赖的最重要的东西，netty，是从JBoss这个Servlet容器项目中独立出去的，一味贬损Servlet会让你自身的立场变得很尴尬。

**Comment by greenlaw110** [comment]
> 但是你看看blade依赖的最重要的东西，netty，是从JBoss这个Servlet容器项目中独立出去的，一味贬损Servlet会让你自身的立场变得很尴尬。

Servlet 是 Sun 很早以前开发的 Java Web 服务架构,其中还能隐约看到 applet 的影子. 之所以 Servlet 到今天都影响巨大, 我觉得一个很重要的原因是 Sun 将其标准化了. 但是以今天的眼光来看, Servlet 并不是一个理想的 web 服务架构.

Netty 是从 JBoss 分离的, 后来 (Wildfly) 还出了 Undertow, 如果说这两者都还有 Servlet 的渊源, 那同样出自 Redhat 的 vertx 已经完全脱离了 Servlet 体系. 由此可知 Servlet 并非 Java web 开发唯一之道. 

反过来说 @dongm2ez 并没有一味贬低 Servlet, 也看不出其立场会变得尴尬的道理. 当然也没有理由说 vertx 的推出会让 Rethat 的立场变得尴尬, 不是吗?

**Comment by caoli5288** [comment]
这里并没有讨论vert.x，vert.x的背景是node.js的流行，甚至原始版本的名字就叫node.x，跟这里讨论的servlet优缺点没有丝毫的联系。

servlet容器提供的快速部署，和一个更上级的controller在很多系统里都能提供巨大的便利，去掉servlet后需要引入大量的额外设施和复杂度才能重新实现这两点，就算现在微服务流行，servlet也不是一无是处了。

我不是前端程序员，也并不想为一个用得不多的东西辩护太多，这个话题到此为止把。

目前为止blade对我来说就是个简单好用的restful框架。之前一直用jersy，jersy支持servlet部署也支持单jar部署，所以api比blade麻烦多了。

**Comment by greenlaw110** [comment]
> 这里并没有讨论vert.x，vert.x的背景是node.js的流行，甚至原始版本的名字就叫node.x，跟这里讨论的servlet优缺点没有丝毫的联系。

讨论 Servlet 优缺点应该在 Java web 开发这个 topic 下面来进行. Vert.x 是一种新的 Java web 开发架构, 提到 Vert.x 就是为了说明离开 Servlet 架构并非一定就是错误的,或者说是"让立场变得尴尬"的做法

> servlet容器提供的快速部署

Servlet 容器本身的部署已经是一个额外的工作了.

> 和一个更上级的controller在很多系统里都能提供巨大的便利，

没有理解你的这句话表达的意思.


> 去掉servlet后需要引入大量的额外设施和复杂度才能重新实现这两点

什么额外的设施,什么复杂度?

**Comment by caoli5288** [comment]
@greenlaw110 我说了servlet话题到此为止，争论起来毫无意义。另外，vert.x是个并发框架，web只是它的一部分，同样的web也只是Java的一部分，包括这个项目，blade，也不是只能拿来写web，这一点，我在之前的comment已经强调过了，

个人爱好minecraft，你可以看到我这个github账号的repo里几乎全是自己写的minecraft插件，contribute过的java项目最近的就有jsoniter-java等等，加起来几万行代码可没有一行跟web有关系，工作数年来主要工作语言也一直是Java，给公司写的代码里面也仅有一次写过一个web中间件，

烦请你不要看到任何Java的东西就自动联想到web上。

**Comment by dongm2ez** [comment]
我想我们的争论可以停止了。

这个项目使用这样的架构是因为觉得这个架构的复杂性小，努力去掉开发的复杂性，降低开发的成本，这是这个框架的哲学和核心思想，这个框架还不完善，也刚从个人项目转由社区维护，会接受不同的意见，欢迎所有的开发者提出意见。以帮助社区发展和完善这个项目。

我个人观点，java EE 的规范束缚了我们的开发思维，有的时候这种束缚是好的，有的时候又不是那么好的，具体得看场景和需求。
