### ISSUE TITLE
Who's using it?

### ISSUE THREAD

**Issue by hellokaton** [lets-blade/blade#144]
If you are using Blade, please send your web site, company or project name record below. We'll synchronize that information right away,  [who's using it?](https://lets-blade.com/about/who-used)
The format is as follows:

- Company：Google
- Project: My Blog
- WebSite：https://example.com

----

Thank you for choosing Blade 💖

**Comment by hellokaton** [comment]
- Project: Tale Blog
- WebSite: https://github.com/otale/tale

**Comment by BestSera** [comment]
- Project: 方方 Blog
- WebSite: [https://fangfang.ink](https://fangfang.ink)

**Comment by realjohnnywu** [comment]
- Project：宝宝和豆豆的那些事
- WebSite：https://www.myann.cn

**Comment by liuyouth** [comment]
- Project: NEXT TO YOU - 小白
- WebSite: http://116.196.122.228:9000/

**Comment by hongquan66** [comment]
- Project: HongQuan's Blog
- WebSite: https://www.devtool.top

博客主题：[otale/theme_handsome](https://github.com/otale/theme_handsome)

**Comment by yai-dev** [comment]
- Project: SUNZHENYU.NET
- WebSite: http://sunzhenyu.net

**Comment by istrwei** [comment]
![tomcat](https://i.loli.net/2017/11/03/59fc1cb7e6651.jpg)

**Comment by SpringSwordh** [comment]
Project: 燃烧吧！小宇宙
WebSite: http://ranshaoba.xyz

**Comment by istrwei** [comment]
![hahah](https://i.loli.net/2017/11/03/59fc1dadee125.png)

**Comment by rubySha** [comment]
- Project: Sav
- WebSite: 待定

**Comment by wuao** [comment]
- Project: moretime 博客
- WebSite:  http://www.moretime.vip/

**Comment by geeker1234** [comment]
- Project: 听风阁
- WebSite: http://www.itviki.com

**Comment by datayang** [comment]
- Project: data羊
- WebSite: https://www.datayang.com

**Comment by MaRuifu** [comment]
Project: 小马哥的故事
WebSite: http://maruifu.cn

**Comment by otuta** [comment]
- Project: Blade Demos
- WebSite: https://github.com/lets-blade/blade-demos

**Comment by wuao** [comment]
@MaRuifu  跪求大佬 博客主题  觉得首页旁边的 好帅气

**Comment by MaRuifu** [comment]
@wuao 就是个JS  下班给你

**Comment by hellokaton** [comment]
- Project: 匿名聊天应用
- WebSite: https://github.com/biezhi/freechat

**Comment by jaytangchn** [comment]
- Project: 萌萌哒的杰哥(personal blog)
- WebSite: http://jaytang.me

**Comment by dzy0302** [comment]
- Project: FindMyFUN
- WebSite: https://www.findmyfun.cn

**Comment by zealzhangz** [comment]
- Project: 海阔天空的博客
-  WebSite: https://www.zhangaoo.com

**Comment by tuzhao** [comment]
- Project: tuzhao's blog
- WebSite: [https://tuzhao.org/](https://tuzhao.org/)

**Comment by HuRuWo** [comment]
- Project: 使用blabe 开发app 后台
- WebSite: https://github.com/HuRuWo/LearnRESTfulApi

**Comment by dongdaxiaodong** [comment]
+ Project:使用blade完成学校的课程设计的后台
+ website: https://github.com/dongdaxiaodong/neuDataStructureProject

**Comment by ebottabi** [comment]
Company：VoyanceHQ
Project: SaaS ML
WebSite：http://voyancehq.com/

**Comment by yimiyisu** [comment]
Company：YimiYisu
Project: kooteam
WebSite：https://www.kooteam.com/

**Comment by wuao** [comment]
感谢您的来信!请您有事去我的新博客：[恒星]http://my.oschina.net/wuao/blog生命不灭的恒星  当梦想擦撞到现实  请不要轻言放弃！
