### ISSUE TITLE
Support yaml configuration

### ISSUE THREAD

**Issue by yai-dev** [lets-blade/blade#149]
### Why use YMAL?  
As we all know,YAML Language is more simplify than Properties and better than that, if use YAML to write configuration files, we can more intuitive to modify the configuration files, and the YMAL is more elegant than Properties.  

### How to achieve?  
Extensions, will not affect the framework size.If needed, add declaration to 'pom.xml' or 'gradle.build'.

**Comment by hellokaton** [comment]
Thanks for your advice. I'll look it later.
