### ISSUE TITLE
Add a timer task tool class

### ISSUE THREAD

**Issue by hellokaton** [lets-blade/blade#172]
- Class Name: `TaskKit`

The class responsibilities:

- Provide a static method to start the task
- Provide a static method to shutdown the task

**Comment by netodevel** [comment]
@biezhi 
Hey, how about an annotation for this functionality?


```java
public class MyFunc {

   @Schedule (cronJob = "* * * * * *")
   public void test () {
       System.out.println ("test cronJob ()");
   }

}
```

**Comment by hellokaton** [comment]
@NetoDevel cool, component management task schedule, annotation-driven, I think it's great and thank you for your continued support.
