### ISSUE TITLE
Add @Value annotation to inject config

### ISSUE THREAD

**Issue by ccqy66** [lets-blade/blade#173]
like Spring @Value and provide the following functions
-  automatic inject config from app.properties：

app.properties
```
rquestUrl=www.xxxx.com
```
UserService.java

```@Bean
public class UserService {
    @Value(name = "rquestUrl")
    private String rquestUrl;
}
```
- Identifying different environments
Benefited from Environment

**Comment by hellokaton** [comment]
This is a good idea, at the same time, you can also join the idea of ​​class management configuration, like:

```java
@Value(name = "jdbc")
public class JdbcConfig {
    private String url;
    private String username;
    private String password;
}
```

**Comment by ccqy66** [comment]
well,it is cool.

**Comment by hellokaton** [comment]
https://github.com/lets-blade/blade/commit/2247d49e1ef936b10f4e3c7543c94fb63e699ce4
