### ISSUE TITLE
请问可以修改json 固定返回的字段吗

### ISSUE THREAD

**Issue by HuRuWo** [lets-blade/blade#194]
```bash
{"payload":null,"success":true,"msg":null,"code":-1,"timestamp":1516264527}
```

类似这种 我想修改 payload为 data success 为int 类型 timestamp 修改格式

**Comment by hellokaton** [comment]
可以的，你不使用自带的 [RestResponse](https://github.com/lets-blade/blade/blob/master/src/main/java/com/blade/mvc/ui/RestResponse.java) 类，而是自己实现一个，也就是拿 `RestResponse` 类修改一下就 Ok 了，使用的时候返回值用自己的类。

**Comment by HuRuWo** [comment]
我的想法也是这样的 请问有相关的群/社区 交流吗

**Comment by hellokaton** [comment]
QQ群：1013565
