### ISSUE TITLE
Restful url support regular expression

### ISSUE THREAD

**Issue by ccqy66** [lets-blade/blade#198]
when we have a url:
`/user/action/:userid` ===> ControllerA
but we also hope the follow mapping:
`/users/action/:userid` ===> ControllerA

so we can config path: 
`/{user:user[s]?}/action/:userid` for ControllerA

now:
both `/user/action/:userid` and `/users/action/:userid` will visit ControllerA

**Comment by hellokaton** [comment]
blade need this feature, in the grounds of the old version is not a member of the regular expression to use lower frequency, but adding this feature is a good choice, great 👍
