### ISSUE TITLE
Windows平台下启动服务，http客户端断开连接会抛出异常

### ISSUE THREAD

**Issue by Succy** [lets-blade/blade#205]
使用的是`blade2.0.5-RELEASE`搭建的mvc服务，使用浏览器提交请求时没有问题，但是使用别的http客户端提交请求时候，会抛出netty的远程强制关闭主机异常，请问作者这个可以解决下吗？
<br>经过测试，在Windows下才会抛出这个异常，在Linux下是不会的，可能是因为Linux的IO模型是用epoll吧，此外，想问下作者，如何开启EpollEventLoopGroup呢？我看代码里边在BladeKit里边判断，但是里面是通过反射获取io.netty.channel.epoll.Epoll.isAvalible方法的返回，但是netty底下的包是没有这个方法的，难道要自己实现一个吗？建议通过配置文件设置。
<br>另外，似乎有几个单词错了，

ps：我猜 `Epool -> Epoll`, `WebSockerHandler -> WebSocketHandler`

**Comment by hellokaton** [comment]
😀感谢你的反馈，`Epool -> Epoll ` 在 `2.0.6-BETA` 修正过了，`WebSockerHandler` 下个版本会修正。
Windows 下的连接断开问题还在排查，不影响功能。

**Comment by cooljgh** [comment]
这个问题能优先改一下吗？非常感谢！

**Comment by cooljgh** [comment]
blade非常好用！
当前这个问题能改一下吗？非常感谢！@biezhi
问题的产生应该是没有处理http头的Connection，浏览器默认都是Connection: Keep-Alive，复用一个socket长连接。
自定义的http客户端如果没有使用连接池，是短连接，Connection: Close，发送完请求就关闭连接。造成blade报异常。还会导致另外一个问题，就是如果客户端没有处理http的长度，即使已经收完数据包，因为不会主队断开连接，会一直等待blade发送数据（实际上已发送完成）。如果客户端主动断开，blade又会抛异常。
解决办法应该是executeLogic中判断Connection，决定是否在writeResponse完成后服务端主动关闭当前连接。ctx.close() ?
