### ISSUE TITLE
如何获取请求头以及返回响应码

### ISSUE THREAD

**Issue by NanayaHaruki** [lets-blade/blade#222]
请求头在request里，响应码在response里?可是在下面的方法里怎么拿到呢
```kotlin
@GetRoute("user/:id")
    @JSON
    fun getUser(@PathParam id: Long?): BaseDTO<*> {
        return if (id != null) {
            val user = Anima.select().from(User::class.java).byId(id)
            if (user != null) ResponseKit.ok(user)
            else ResponseKit.fail(StrConst.NO_DATA)
        } else ResponseKit.fail("id不可为空")
    }
```

**Comment by hellokaton** [comment]
`Response` 对象中提供一个 `statusCode()` 方法可以获取到相应状态码，你也可以调用这几个方法修改状态码
![image](https://user-images.githubusercontent.com/3849072/38595571-362b86da-3d7f-11e8-81c5-58036a7a6e62.png)

**Comment by NanayaHaruki** [comment]
仔细看了下readme，似乎只要把request  response加入控制器方法的参数就可以拿到了,header可以用request拿也可以用注解拿。
```kotlin
@GetRoute("user/:id")
    @JSON
    fun getUser(@PathParam id: Long?,
                       @HeaderParam headtest:String,
                       response: Response): BaseDTO<*> {
       response.status(404)
        return ...
```
如果要自己设置状态码必须这样把response放进参数再改么  总觉得每个方法都这么干不是很优雅？我看RestResponse里success（false）也都是200，要根据具体的失败原因要返回不同的状态码，有什么其他方式吗

**Comment by hellokaton** [comment]
@Ayanokouji-Kenn 有静态方法的方式，但我觉得都是一样的，即便不加入 `Response` 参数进来，使用 `WebContext.response().status(503)` 其实差不了多少的。也有一种 `API` 的设计会将 `Request` 和 `Response` 的操作打包为一个 `XXContext` 对象，一起操作；我认为这种方式无法明确操作的到底是请求还是响应，所以 Blade 没这么做。

`RestResponse.success` 为 `false` 返回 200，实际上应该调用 `RestResponse.fail(code, msg)` 当然为 false 的情况下框架也不知道应该返回 `4xx` 还是 `5xx` 。
