### ISSUE TITLE
How to package as war?

### ISSUE THREAD

**Issue by zenglian** [lets-blade/blade#230]
How to package the app as war?   e.g., I'd like to deploy to Tomcat.

**Comment by chenshun00** [comment]
Use  `nohup java -jar xxx.jar &` can be deployed

The implementation of `Blade` does not comply with the specifications of Servelt. and there is no webapp directory ，Maybe you can use `Listener` to let tomcat launch the blade.

**Comment by hellokaton** [comment]
@zenglian  `JAR` package is web server, you don't need to care about `Tomcat`.
