### ISSUE TITLE
Gradle 如何打包？

### ISSUE THREAD

**Issue by mapleafgo** [lets-blade/blade#232]
官网只讲了Maven打包，Gradle是否有打包方法？

**Comment by hellokaton** [comment]
我正在为 `gradle` 结构编写一些示例程序，代码会存储在 [这里](https://github.com/lets-blade/gradle-examples)

**Comment by hellokaton** [comment]
@fanlide 打包写了2个示例，分别是 [打一个单独jar](https://github.com/lets-blade/gradle-examples/tree/master/gradle-pack01) 和 [打一个目录形式的包](https://github.com/lets-blade/gradle-examples/tree/master/gradle-pack02)。

如果你在打包这里有什么问题，可以继续在该 `issue` 反馈。
