### ISSUE TITLE
问个题外话

### ISSUE THREAD

**Issue by WisdomFamily** [lets-blade/blade#233]
发现blade特别好用，微服务这种架构目前spring boot特别火，但是blade相比spring boot很轻量，很好用，就不知道为啥这么好的blade没有火到spring boot那种程度。哎，好东西都埋没了

**Comment by hellokaton** [comment]
1. 社区
2. 成熟度
3. 在很多项目的实践
4. 生态

这个程序大部分都是我在维护，一般发布版本也很少宣传、推广，有一部分的使用者。
因为没有更多的维护者，用户数一旦多了我也处理不过来，所以目前也就是一周更新一次的样子。
也希望听到一些大牛的建设性建议，包括以上提出的 4 点。

不过 Blade 也只是整个 Java 生态链的其中一个选择，也不必太过于关注它是否多么的火。有更多的用户/受众当然是高兴的，未来完善的越来越好，给开发者带来思想和效率上的提升是它存在的意义。

**Comment by aqnaruto** [comment]
不就是一个抄袭的框架吗，而且核心的东西像异步，抄不会就没有，加了几次群还不让进，可见作者之狭隘。

**Comment by ccqy66** [comment]
@aqnaruto 从你的措辞看出，你应该是个很厉害的大牛，不如贡献一个框架让大家学习学习吧。

**Comment by aqnaruto** [comment]
@ccqy66 我只是说句实话而已，原创的东西几乎没有 全是rapidoid和act的。 act和jfinal作者都虚怀若谷热情如火，和抄袭者 的姿态 高下立判

**Comment by hellokaton** [comment]
@aqnaruto 

**说 Blade 是抄袭的，无理取闹？**

Blade 诞生于 2015 年，`JFinal` 更早一些，我确实也看过 `JFinal` 的源码，包括 `act` 的使用我也看过，至于你说的 `rapidoid` 我没听过谢谢。 做 Web 框架这块，几乎所有编程语言的设计思路都是类似的，框架总是百家争鸣的状态，这在任何编程语言中都是如此。`act` 的作者也为 Blade 做过贡献难道别人就不知道还需要你来指出？你怎么就知道没有原创的东西，你又凭什么说 **全是rapidoid和act的** ？

**act和jfinal作者都虚怀若谷热情如火，和抄袭者 的姿态 高下立判**

这又是什么意思？难道 Linux 的作者还要天天面对你这种无聊的人？还高下立判，对不起我没兴趣和为开源做贡献的任何人引战，这世界不需要你这种人来不断的制造硝烟。

从你的口吻 **不就是一个抄袭的框架吗** 这不是对待开源的态度，所以你也没有资格来评判它。**核心的东西像异步**，这好像是你内心的想法吧，Blade 没说过要做异步化这块啊？你是从何了解它 _抄_ 不会的呢？

加了群不让进，那你为什么没有发邮件呢？我总不能每天蹲着 QQ 吧？你说我狭隘，我貌似和你没有一句话的交谈也没有一面之谈，你这样评价一个人你觉得你自己合适吗？

**往往技术水平越低的人 稍微得志就喜欢故作姿态**

1. 我没有自称过水平高，故作姿态也是你的内心想法而已
2. 就算一个人故作姿态或是高傲，怕是只会针对你这种人吧

**Comment by 80000v** [comment]
@aqnaruto 作者也就是群主由于工作繁忙不经常在qq群里，然而刚才群里的管理员贴出了几张图，你这个态度有问题，也不能怪人家不让你进群了，别人进群都是交流学习的，你进群想干什么。我们不得而知。
![image](https://ws2.sinaimg.cn/large/005QwKRQgy1frs2xn1ct1j30u80k20uw.jpg)
![image](https://ws2.sinaimg.cn/large/005QwKRQgy1frs308gbkkj30ni08adgs.jpg)

**Comment by tangxang** [comment]
精神病人，欢乐多

**Comment by aqnaruto** [comment]
我现在暂时还没有多余时间研究比对代码，暂且收回抄袭这种未经考据的调调。
为什么有抄袭嫌疑，主要是因为 main方法里 可以直接写路由 通过java8的闭包 节省了冗余代码。 这一段实现跟rapidoid简直一模一样，
这种写法 像
On.get("/size").json((String msg) -> msg.length());
On.any("/words").json(() -> JPA.of(Word.class).all());
一行代码就是一个路由 完成一个api功能 这非常酷。因为其实在路由方法里 特别是restful的，return关键字和方法前的类型声明  基本上都是没有任何作用的。
当前rapidoid的缺点是 这种路由只能写在main里，这样做的缺点是不能像写在一个controller的类里可以做通用处理，方便管理。为什么连缺点也要一样呢？如果你有意修改这个缺点，是可以实现放在类里的。
blade沿袭了rapidoid的优点， 也沿袭了缺点（因此值得怀疑）

对比rapidoid，两者都是比较简的框架，blade稍微丰富一点，但是基本上可以认为是一样，但rapidoid是异步化的，性能登顶java web框架性能之巅。我选act是因为它配件周全，至少最基本常用的它提供了。选rapidoid 是因为极客 炫酷 极致性能。那blade还能给开发者带来什么别的用处？

**Comment by aqnaruto** [comment]
此外，对比actframework,     act 至少参与了性能网站的排名 能拿到可观的名次，act周边配件更多，像websocket，上传下载，邮件，事件调度等 使用起来更加方便。因此，actframework 和blade代码编写上类似，但是功能更全，作者更热心，性能可以上榜，为什么我还要用blade。
还有，blade的一些api命名不好 比如 Blade.me()  , me是什么意思？对于有洁癖的人来说 每次用这个me都有点不爽。
要说blade优点 也不是一点没有，主要是文档清晰，美观，阅读舒适。

**Comment by hellokaton** [comment]
@aqnaruto 你有选择不用的权利，但你不能代表所有人。你可以评价一个东西不好，不代表它永远不好，关于使用者提出不足之处我们从未说过置之不理。

如你所说的邮件这些功能不是 web 框架应该考虑的范畴，确实属于 web 领域的常用功能，如果我使用 `sendgrid` 这样的第三方那么这功能就是鸡肋了（当然我说这话也不代表大多数，所以选择是具有两面性的）。

**Comment by hellokaton** [comment]
@aqnaruto 关于你说 api 命名，我刚才看了下 `rapidoid`。

![image](https://user-images.githubusercontent.com/3849072/41209837-8fceafee-6d60-11e8-9379-e37d435f5f56.png)

我也想表示我不懂 `On` 是什么意思？不是注册路由吗，那为什么不用 `Router` ? 我没有深究这个，我想作者会有自己的定义。

**Comment by aqnaruto** [comment]
我不能代表所有人，我只能代表我自己，当我评价的时候，因为我内心有期待才会评价，就像玩一款游戏，希望他更好才会评价。我这种评价是很正常的，经得起赞美就经得起诋毁，就算体育如世界冠军，科研如北斗龙芯照样如此，费劲做出来 没有功劳也有苦劳 但是却有人bb不停 负影响被评价者。
on比me好点，on 至少可以理解为 “当”   ，希望不要打击到您的开源热情，我嫌弃spring  嫌弃 laravel yaf yii嫌弃 thinkphp5 我这人一向如此。

**Comment by 100cm** [comment]
@aqnaruto 
![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)![image](https://user-images.githubusercontent.com/12691638/41211177-3afa8f3a-6d68-11e8-8d07-d30c9b3b9a13.png)

**Comment by hellokaton** [comment]
不会打击到的，你反馈的问题我会考虑的，开源软件本应收到鼓励或批评，只要意见是正确的我觉得理性者都该接受，但论事避免人身攻击才能促进发展。
