### ISSUE TITLE
可以尝试添加 jsr305 注解

### ISSUE THREAD

**Issue by ChunMengLu** [lets-blade/blade#241]
我昨天研究了下这个感觉蛮不错。

Spring-core中的jsr 305相关注解：
https://github.com/spring-projects/spring-framework/tree/master/spring-core/src/main/java/org/springframework/lang
```java
@NonNull
@NonNullApi
@NonNullFields
@Nullable
```
### 依赖
```java
 // JSR-305 only used for non-required meta-annotations
compileOnly("com.google.code.findbugs:jsr305:3.0.2")
testCompileOnly("com.google.code.findbugs:jsr305:3.0.2")
```
### IDEA中的效果
![jsr-305](https://user-images.githubusercontent.com/2115440/40846897-73bd59ba-65ed-11e8-9b18-d9886e636cb5.png)

**Comment by hellokaton** [comment]
目前已经使用了 lombok，这些特性是有的。
