### ISSUE TITLE
静态资源问题

### ISSUE THREAD

**Issue by starfire-lzd** [lets-blade/blade#248]
Please provide the following information if applicable:
我跑了demo，设置了静态资源的路径，但是返回得到的是404，
- deepin 15.5
- Build tools (gradle)
- JDK version（1.8） and blade version(e.g `2.0.8-R1`)

**Comment by hellokaton** [comment]
@starfire-lzd 你是运行 [gradle-example](https://github.com/lets-blade/gradle-examples) 的例子吗？
如何启动应用的？

**Comment by starfire-lzd** [comment]
我是按照教程自己搭建的例子，使用的是intellij IDEA启动的，我追查源码发现在`StaticFileHandler.java`中的第119行`resourcesDirectory.getPath() + "/resources/" `的代码中多添加了一个resources路径，在120行中file的路径里面有两个resources

**Comment by starfire-lzd** [comment]
我使用的构建工具是gradle

**Comment by starfire-lzd** [comment]
我把代码拉下来，将
`resourcesDirectory.getPath()`
替换成
`resourcesDirectory.getParent()`
重新编译之后结果正常了

**Comment by hellokaton** [comment]
我会继续尝试这个问题，我在 gradle 下运行上面的例子是没问题的，方便的话可以贴出你的项目地址。

**Comment by yai-dev** [comment]
我遇到了同样的问题，同样是Gradle项目
