### ISSUE TITLE
consider support reactive api

### ISSUE THREAD

**Issue by ccqy66** [lets-blade/blade#252]
Reactive programing is a nice model, do you think whether blade support reactive api？

**Comment by hellokaton** [comment]
I'm glad that someone also thinks about this. I've considered this issue, so the current `snapshot` version is optimized for code. I thought about designing an extended `Future` as the return value of the `Route` logic method, it will be a little easier, but I don't know if this way will get everyone's support. In addition to this, if there is a better way to implement it, I'm willing to listen.

This feature is equivalent to creating a thread pool inside the `Blade` to maintain these asynchronous tasks in the `IO` processing (netty woker), at the same time need to consider compatible with the old version and context (WebContext) settings.

The reason why haven’t done it yet is that worried that multiple thread pools can cause performance to fail to improve.

**Comment by hellokaton** [comment]
code like 

```java
public ViewFuture indexPage(){
    return ViewFuture.execute(ctx -> {
        // do something
        return ViewFuture.render();
    });
}

public RestFuture jsonData(){
    return RestFuture.execute(ctx -> {
        // do something
        return RestFuture.success();
    });
}
```

**Comment by ccqy66** [comment]
emmm，
I just have a original idea，and I think blade built-in reactive api,will more simplify `IO` processing,and the more powerful.

you can see:
https://docs.spring.io/spring/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/web-reactive.html

**Comment by chenshun00** [comment]
@ccqy66 @biezhi there is more infomation or data about `reactive-model` and `Reactive Stacks` , i  find a video from infoQ. [Servlet vs Reactive Stacks in Five Use Cases](https://www.infoq.com/presentations/servlet-reactive-stack)

**Comment by crossoverJie** [comment]
I think this feature is useful and keep focusing.
