### ISSUE TITLE
內存泄漏嫌疑

### ISSUE THREAD

**Issue by jonastanstevens2016** [lets-blade/blade#254]
`Blade.java` 132行：   

```java
private Server server = new NettyServer();
```

864行：`server.start(Blade.this, args);`

`NettyServer.java` 106~107行：    

```java
public void start(Blade blade, String[] args) throws Exception {
    this.blade = blade;
}
```

這兩段代碼會泄漏內存。blade和server對象的指針會構成循環引用。
無法單獨回收其中一個。盡管整個 `server` 一直跑，也不是個好的 `OO design`

**Comment by hellokaton** [comment]
@jonastanstevens2016 感谢你的反馈，可以贴一下版本号吗？这个问题如何重现？

**Comment by ccqy66** [comment]
@biezhi 感觉他的意思是说，`NettyServer`和`Blade`两个类分别持有了对方的对象引入，导致gc无法针对两者任一个对象进行gc。从而导致`内存泄露`
我对内存泄露的理解是：申请的内存本该释放，但是由于某种原因没有达到释放。但是从该代码的逻辑上来看，应该是不存在这种需要释放二者之一的场景。从类的关系设计上看，二者也存在关联关系。

**Comment by hellokaton** [comment]
`NettyServer` 和 `Blade` 类确实是相互依赖的，最好的设计是单方依赖（但这在很多时候是不可能的）。
内存泄漏的问题我无法重现出来，我通过 `JProfiler` 观察内存变化还算正常。

**Comment by hellokaton** [comment]
暂时关闭，如可重现继续评论。
