### ISSUE TITLE
Json response compressions

### ISSUE THREAD

**Issue by Yousefjb** [lets-blade/blade#259]
Please provide the following information if applicable:

- Operating system and its version
Windows 10 15063
- Build tools (e.g. maven or gradle)
maven
- JDK version and blade version(e.g `2.0.8-R1`)
JDK 1.8, blade 2.0.8-R1

How can I return gzipped json response ?   
Also `Balde.me().gzip(true) `seems to do nothing, what does it exactly do ?

Thanks

**Comment by ccqy66** [comment]
blade as a server for netty, so `HttpContentCompressor` must be tail in the pipeline to guarantee high priority to execute . also because `HttpContentCompressor` is a `ChannelOutboundHandler`
#260

**Comment by hellokaton** [comment]
@ccqy66 😂Sorry, I didn't see this PR. This has been fixed in the `dev` branch, at the same time, the gzip of the file is processed.

This feature is currently available in version `2.0.9-SNAPSHOT`.

**Comment by ccqy66** [comment]
ok,good job.
