### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by ChunMengLu** [lets-blade/blade#26]
1. `PatternKit.java`的`isMobile`加上170的手机号，曾经不少网站出现这个bug ~.~
2. 建议把environment(环境变量)纳入底层，内部定义好三个环境，根据不同（环境+机器）判断加载不同配置文件等。
3. http://bladejava.com/ 网址下的爬虫能力下面的`查看详细代码`地址应该是改了！

**Comment by hellokaton** [comment]
Good idea, Thanks :smile:
