### ISSUE TITLE
企业级开发

### ISSUE THREAD

**Issue by mallxiaodoudou** [lets-blade/blade#265]
本人新入门小白，我看到你的视频说不支持企业级的开发，只面向个人开发者，为什么说不支持呢？是性能的原因还是拓展的原因？和SSM框架对比缺点是哪些？我该如何抉择？。。。那我想在公司项目中使用该框架。有什么需要注意的？

**Comment by hellokaton** [comment]
@liukai2530533 因为企业级开发往往会集成很多第三方组件，比如消息中间件、RPC服务、分布式事务等较为重的组件。而 Blade 是没有和这些软件做集成的，所以如果真的这么干需要自行去操作，比如 Spring 会提供一系列的套件拿来直接用，如果你的产品没这么复杂，当然可以使用 Blade。

**Comment by mallxiaodoudou** [comment]
2018/07/25 13:29:51  WARN [   worker@threadㄧ1 ]         c.b.m.u.t.DefaultEngine : View path is: \templates\index.html
2018/07/25 13:29:51 ERROR [   worker@threadㄧ1 ]      c.b.s.n.RouteMethodHandler : Render view error com.blade.exception.TemplateException: java.lang.NullPointerException
![tkmu px19s24 g a23uyvi](https://user-images.githubusercontent.com/23752905/43181361-47ff468e-900f-11e8-9ada-5db3b2e049b8.png)

还有一个问题！我打成jar包运行，为什么不能跳转template的html，直接运行java完美运行，,打成jar包其他接口都能正常返回，就是template中的html不行，这是什么原因

**Comment by mallxiaodoudou** [comment]
jar包环境下直接访问http://127.0.0.1:9002/templates/index.html是可以访问的，就只是在jar包环境下的context.render("index.html"); 不能正常跳转

**Comment by hellokaton** [comment]
@liukai2530533  打包方式可能有问题，在 Blade 中可以使用 2 种方式进行打包。

1. 打单个 `jar` 包
2. 打成一个目录

生产环境推荐第二种。

**第一种方式**

在 `pom` 中添加一个插件

```xml
<plugin>
    <artifactId>maven-assembly-plugin</artifactId>
    <configuration>
        <finalName>${project.build.finalName}</finalName>
        <appendAssemblyId>false</appendAssemblyId>
        <archive>
            <manifest>
                <mainClass>你的运行主类</mainClass>
            </manifest>
        </archive>
        <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
    </configuration>
    <executions>
        <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
                <goal>single</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

可参考 [pom.xml](https://github.com/lets-blade/blade-demos/blob/master/blade-helloworld/pom.xml)

**第二种方式**

1. 添加一个 `package.xml`
2. 添加 `maven-assembly-plugin` 插件和 `maven-jar-plugin` 插件

参考 [blade-package](https://github.com/lets-blade/blade-demos/blob/master/blade-package/pom.xml) 项目。

**Comment by mallxiaodoudou** [comment]
第二种方法可以了，多谢

**Comment by hellokaton** [comment]
欢迎反馈你的问题，这个 `issue` 我关闭了。
