### ISSUE TITLE
OutputStreamWrapper类ctx没有初始化

### ISSUE THREAD

**Issue by programlife555** [lets-blade/blade#266]
OutputStreamWrapper类ctx没有初始化，报错。

**Comment by hellokaton** [comment]
@programlife555 贴一下你的代码片段，这个问题明天我会跟进。

**Comment by programlife555** [comment]
https://github.com/lets-blade/blade/blob/master/src/main/java/com/blade/mvc/wrapper/OutputStreamWrapper.java

**Comment by hellokaton** [comment]
@programlife555 你怎么调用它的，是下载吗？

**Comment by static-mkk** [comment]
@biezhi   OutputStreamWrapper是构造器里面，忘记啊ChannelHandlerContext ctx;参数类。。。  
    在41行。

**Comment by wuma2020** [comment]
@biezhi  在OutputStreamWrapper是构造器里面，忘记把ChannelHandlerContext ctx;参数传进去了。。。
在41行。

**Comment by hellokaton** [comment]
@static-mkk 我准备修改这里的代码，我感兴趣的是别人如何使用的？

**Comment by wuma2020** [comment]
好的。

**Comment by GISering** [comment]
> @static-mkk 我准备修改这里的代码，我感兴趣的是别人如何使用的？

这个bug什么时候可以修复啊，项目写的图片访问的控制器，卡在这里了~~~感谢！！！

**Comment by hellokaton** [comment]
@GISering 你是用于什么功能呢? 下载图片还是

**Comment by GISering** [comment]
下载图片，把图片流写入Response

**Comment by Tush-r** [comment]
Can someone provide some code to reproduce the bug?
