### ISSUE TITLE
如何将输入流  返回个请求客户端 然后以流的形式下载文件

### ISSUE THREAD

**Issue by songlongkuan** [lets-blade/blade#268]
目前我的写法是这样的 但是并没有效果
 StreamBody streamBody = new StreamBody(fileName, httpResponeBody.body().byteStream());
 response.contentType("video/mp4");
 response.body(streamBody);

**Comment by hellokaton** [comment]
@pencilso 输入的内容是什么？

**Comment by songlongkuan** [comment]
inputStream

**Comment by songlongkuan** [comment]
我整个的流程是这样的
因为 一些限制的原因  
客户端 不可以直接下载一些文件 所以会通过服务器中转的形式来下载  
例如：xx.com/download?url=https://xx.com/mv.mp4
download这个接口 接收到url参数  然后呢 这时候服务器通过url 打开输入流
然后再通过response 将获得的输入流 给response的输出流
以此达到中转下载的效果

**Comment by songlongkuan** [comment]
不知道我有没有表达的清楚

**Comment by hellokaton** [comment]
@pencilso 目前 Blade 支持客户端以 `form` 表单的形式上传文件，下载文件也是支持的，输入流的方式不支持。

**Comment by songlongkuan** [comment]
是否可以支持？
我没仔细看过Blade的源码，不过我猜测，下载文件，应该也是拿到文件的输入流吧，然后再拿到respone的输出流，再然后就是从文件的输入流里读取字节，再写入到输出流，以此达到下载的效果。
那么直接开放一个inputStream的响应接口，是不是就可以呢。

**Comment by GISering** [comment]
我倒是找到办法把图片流写入response body里，但是通过

 _OutputStreamWrapper osw = response.outputStream();
 osw.write(data);
 osw.close();_

最后close时报空指针，调试发现 _**OutputStreamWrapper**_  成员变量  _**ctx**_ 为null


_public class OutputStreamWrapper implements Closeable, Flushable {
      private OutputStream          outputStream;
      private File                  file;
      private ChannelHandlerContext ctx;
}_ 
@biezhi

**Comment by songlongkuan** [comment]
emmmm.... 已选择使用SpringBoot
