### ISSUE TITLE
有提供1.0版本的源码以供学习吗？

### ISSUE THREAD

**Issue by ikutarian** [lets-blade/blade#270]
想学习blade的源码，但是目前的代码太多了，能否提供1.0的版本以供学习。
方便之后再过度到现在的版本进行学习。

**Comment by dongm2ez** [comment]
当然有，目前blade代码有600多个提交，你可以checkout到最开始那个提交看啊

https://github.com/lets-blade/blade/commit/688d0506dcffc3d356c5ee39edb580883687c120

这就是仓库的第一次提交
