### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by caoli5288** [lets-blade/blade#271]
**Screenshots**
![_2018-09-04t11-33-54 409z](https://user-images.githubusercontent.com/3120587/45029180-6dd56380-b07a-11e8-8174-565b39e70436.png)

Codes like here
```
    @Route("api")
    public RestResponse api(@Param ApiRequest request) {

    }

```

**Comment by hellokaton** [comment]
可否给出详细的信息？比如 `Blade` 版本号，你的 `ApiRequest` 数据结构

**Comment by caoli5288** [comment]
api版本号是2.0.9-BETA.3
数据结构如下，用了lombok
```
@Data
public class ApiRequest {
    private String username;
    private int ban;
    private String reason;
    private String token;
    private String expireDate;
}
```

**Comment by caoli5288** [comment]
是不是get方法不支持@Param转成pojo对象，我看readme里面是post方法

**Comment by hellokaton** [comment]
@caoli5288 `GET` 支持 `@Param` 注解注入参数的，我试了下这个例子是可以的。我的代码是这样的

```java
@GetRoute("api")
@JSON
public ApiRequest apiRequest(@Param ApiRequest apiRequest){
        System.out.println(apiRequest);
        return apiRequest;
}
```

使用浏览器访问：`http://127.0.0.1:9000/api?username=biezhi`

或者 CURL 方式

```bash
# biezhi in ~
» curl http://127.0.0.1:9000/api\?username\=biezhi

{"username":"biezhi","ban":0,"reason":null,"token":null,"expireDate":null}
```

**Comment by caoli5288** [comment]
迷，，由于只是赶工做个简单接口已经直接用`Blade.of().get()`了，记得很久之前也用过你的项目，那时候还没问题的。

**Comment by hellokaton** [comment]
可以的，有问题可以把你的详细情况描述一下，这个 `issue` 先关闭了。
