### ISSUE TITLE
gradle 创建项目的时候，在classpath下面找不到template

### ISSUE THREAD

**Issue by eaglefly** [lets-blade/blade#280]
gradle项目在IDEA下面有编译输出的路径是`out/production/classe`s和`out/production/resources`
导致获取不到页面文件。
修改文件： `FileChangeDetector.getDestPath()  `获取静态文件的方式分两种方式，当从Const.CLASSPATH获取不到的时候在从BladeKit.class.getResource("/templates"").getPath()获取一次

**Comment by eaglefly** [comment]
DefaultEngine修改成如下  
//Const.CLASSPATH
 String resourcePath = this.getClass().getResource("/"+TEMPLATE_PATH).getPath();
 String viewPath = resourcePath + File.separator + view;

**Comment by hellokaton** [comment]
@eaglefly 可否尝试 [这里](https://github.com/lets-blade/gradle-examples) 的例子
