### ISSUE TITLE
Register Route

### ISSUE THREAD

**Issue by ebottabi** [lets-blade/blade#284]
Hi there,

I am getting a java.lang.NullPointerException when using the controller package for routing, given the example below:
```
@Path
public class IndexController {

    @GetRoute("/")
    public String index(Request request){
        return "index.html";
    }
}
```
index.html is available inside the template directory, after compiling via Maven, and accessing on the browser, i get 500 error, when i take off **Request request** from the index method, all works well. Is there a way accessing the request body other than via Request?

Thanks.

**Comment by hellokaton** [comment]
@ebottabi Please provide the `Blade` version you used and your `main` method code.

**Comment by CCweixiao** [comment]
banner.txt怎么加载，放在resources目录下的自定义banner.txt无法加载

**Comment by ebottabi** [comment]
@biezhi sorry for the late response, the version is 2.0.11.BETA
