### ISSUE TITLE
关于readme里what's blade

### ISSUE THREAD

**Issue by immarktube** [lets-blade/blade#286]
我是关注了@biezhi过来看这个项目的，我在readme里what's blade没弄懂这个blade到底是用来做什么的。
能不能直白的告诉我我可以用它来做什么事情，它能为我在那些事情上更好的服务。

**Comment by crossoverJie** [comment]
@VonJane 

简单来说 `SpringMVC` 能做的 `Blade` 也可以，如果你想体验非 `Spring` 生态的应用那么 `Blade` 值的一试。

**Comment by immarktube** [comment]
> @VonJane
> 
> 简单来说 `SpringMVC` 能做的 `Blade` 也可以，如果你想体验非 `Spring` 生态的应用那么 `Blade` 值的一试。

收到收到，over！
