### ISSUE TITLE
请问怎么支持jsp呢？

### ISSUE THREAD

**Issue by Ryziii** [lets-blade/blade#293]
Please provide the following information if applicable:

- Operating system and its version
- Build tools (e.g. maven or gradle)
- JDK version and blade version(e.g `2.0.8-R1`)

在翻阅资料时发现blade早期版本是支持jsp的，现在只支持静态的了，我想用到jsp的功能请问怎样才能开启支持呢？感谢

**Comment by hellokaton** [comment]
目前的版本和未来都不会支持 jsp 了，之前支持 jsp 是因为 web 容器基于 jetty 实现的，但作为视图层的选择 jsp 只是其中之一。

当前 Blade 的版本没有实现 servlet 规范，所以也就不会对 jsp 做支持，不过使用其他模板引擎也是可以达到同样的效果，可以参考 [模板视图](http://lets-blade.com/docs/templates.html)。

有其他疑问可以继续在该 issue 下留言 : )
