### ISSUE TITLE
ctx.render() doesn't work from "java -jar"

### ISSUE THREAD

**Issue by andrea-ligios** [lets-blade/blade#299]
**Describe the bug**

The `ctx.render()` method, as shown in the following code: 

    public static void main(String[] args) {
        Blade.of()
		 .get("/", ctx -> ctx.render("index.html"))
		 .start(Application.class, args);
    }

it DOES work when run from the IDE (**Run as Java Application** from Eclipse)
it DOES NOT work when run from the CLI (`java -jar target\blade-app.jar`)

**To Reproduce**

**Run the attached package with `java -jar`.**

[app.zip](https://github.com/lets-blade/blade/files/2628634/app.zip)

**Screenshots**

From CLI it doesn't work:
![immagine](https://user-images.githubusercontent.com/11974750/49214412-e53f3880-f3c6-11e8-9312-ed0584236cfc.png)

From Eclipse it works:

![immagine](https://user-images.githubusercontent.com/11974750/49214836-c1c8bd80-f3c7-11e8-8d99-a311900a1efe.png)

**Additional context**

I suspect everything is bound to the `app.classpath`. 

Run with the IDE:

    c.b.s.n.NettyServer : app.classpath    => C:/Users/a.ligios/git/blade/app/target/classes/
    
Run with `java -jar`:

    c.b.s.n.NettyServer : app.classpath    => C:\Users\a.ligios\git\blade\app\target\blade-app.jar

**Comment by hellokaton** [comment]
Please try this version`2.0.12.RELEASE` : )

**Comment by andrea-ligios** [comment]
Nope 😞 :

![immagine](https://user-images.githubusercontent.com/11974750/49361431-525f1080-f6dc-11e8-8b0f-22be7804df84.png)

It fixed #297 , though!

Now 2.0.12 works as 2.0.11 (and as every other previous version): yes on the IDE, nope on Windows CLI.

I'll let you know if it runs on Ubuntu ASAP, stay tuned

**Comment by hellokaton** [comment]
Ok, I continue to pay attention to this issue. I have not reproduced it myself. I am letting other collaborators continue to try.

**Comment by andrea-ligios** [comment]
>
> [image: immagine.png]
>

BTW, the error happens AFTER opening the page in the browser;

The screenshot above stops at *"Open browser access http://127.0.0.1:9000
<http://127.0.0.1:9000>":* have you opened the browser page?

Mine too is working *up to that point*...

Cheers


Il giorno ven 30 nov 2018 alle ore 03:17 Zhen Yu <notifications@github.com>
ha scritto:

**Comment by andrea-ligios** [comment]
> I'll let you know if it runs on Ubuntu ASAP, stay tuned

It works perfectly fine on my Ubuntu... **the problem is only on Windows** then:

![schermata da 2018-12-04 23-17-59](https://user-images.githubusercontent.com/11974750/49476750-21392a00-f81b-11e8-8197-948e968942a7.png)

**Comment by hellokaton** [comment]
@andrea-ligios  The `2.0.13.ALPHA` version of the Windows system works.

**Comment by andrea-ligios** [comment]
Perfect! Thank you @biezhi
