### ISSUE TITLE
Uploading file of small sizes such as 3kb to 500Kb throws an exception

### ISSUE THREAD

**Issue by ebottabi** [lets-blade/blade#301]
I am working on an endpoint that handles the upload of csv datasets of sizes ranging from 3Kb to 100Mb. Files of pretty smaller sizes throws an exception of: **Parse request parameter error java.io.IOException: Not represented by a file** whereas if the file is say 2Mb or larger it works. 

Googling around i found this Netty issue on **File corrupted in HTTP Multipart POST** [https://github.com/netty/netty/issues/1727](https://github.com/netty/netty/issues/1727), don't know if it might be the issue. 

Any thoughts or suggestions as to why this happens, will be highly appreciated.

<img width="1343" alt="screen shot 2018-12-01 at 12 52 08 am" src="https://user-images.githubusercontent.com/351587/49320817-225d1500-f504-11e8-8277-0404dae1c46e.png">

Thanks.

**Comment by hellokaton** [comment]
Thanks your feedback, you can try `2.0.12.RELEASE` has fixed this problem.

**Comment by ebottabi** [comment]
Thanks, will do and let you know.
