### ISSUE TITLE
static中img文件夹中的文件部分显示，部分404

### ISSUE THREAD

**Issue by CCweixiao** [lets-blade/blade#305]
同一个文件夹中的图片，部分显示，部分404

**Comment by hellokaton** [comment]
显示部分是否是启动前就加入的，你可以在 `target/classes/static/img` 下看看是否有未显示的文件。

IntelliJ 点击 ![image](https://user-images.githubusercontent.com/3849072/49684827-3f9d6f00-fb14-11e8-8777-643364f67280.png) 即可。
