### ISSUE TITLE
如何取消默认的模板引擎,使后端完全不使用模板

### ISSUE THREAD

**Issue by dongdaxiaodong** [lets-blade/blade#306]
在render了一个html文件后，浏览器报错。查明原因应该是默认引擎'$'字符导致的问题，所以希望知道如何能够取消模板渲染这一步。也尝试换jetbricktemplate,项目报错，运行不了

**Comment by hellokaton** [comment]
参考 [文档](http://lets-blade.com/docs/templates.html) - [代码示例](https://github.com/lets-blade/blade-demos/blob/master/blade-template)

**Comment by dongdaxiaodong** [comment]
太感谢了
