### ISSUE TITLE
Support form object acquisition

### ISSUE THREAD

**Issue by suxinjie** [lets-blade/blade#31]
``` html
<from>
   <input name="person.name">
   <input name="person.phone">
   <input name="person.cardNo">
   ......
</from>
```

``` java
Person person = getModel("person", Person.class);
```

Not specify arg2，default person -> Person

**Comment by hellokaton** [comment]
Support in 1.5.1-beta

**Comment by suxinjie** [comment]
Can you take a look at 1.5.1-beta API,
I would like to add a document.

**Comment by hellokaton** [comment]
The Api Doc see [Here](http://bladejava.com/apidocs/com/blade/web/http/Request.html), and [source code](https://github.com/biezhi/blade/blob/master/blade-core/src/main/java/com/blade/web/http/wrapper/ServletRequest.java)

The method name is `Request.model()`

If you want to add documents, want to change the place [http://bladejava.com/docs/modules/requestresponse](http://bladejava.com/docs/modules/requestresponse)

Remember to add in both Chinese and English both! 

Thank you for your participation, if you encounter any problems can contact with me! :smile:
