### ISSUE TITLE
内置方法WebContext.request().isAjax()判断是否为AJAX的bug

### ISSUE THREAD

**Issue by itomcat666** [lets-blade/blade#313]
在一个请求中我的header返回的是：
`X-Requested-With:XMLHttpRequest`
但是内置方法为：

>  default boolean isAjax() {
        return "XMLHttpRequest".equals(header("x-requested-with"));
    }

>   default String header(@NonNull String name) {
        String header = "";
        if (headers().containsKey(name)) {
                header = headers().get(name);
        } else if (headers().containsKey(name.toLowerCase())) {
                 header = headers().get(name.toLowerCase());
        }
        return header;
    }

显然是无法判断是否为ajax的

**Comment by itomcat666** [comment]
>  var httpHeaders = fullHttpRequest.headers();
        if (httpHeaders.isEmpty()) {
            this.headers = new HashMap<>();
        } else {
            this.headers = new HashMap<>(httpHeaders.size());
            var entryIterator = httpHeaders.iteratorAsString();
            while (entryIterator.hasNext()) {
                var entry = entryIterator.next();
                headers.put(entry.getKey(), entry.getValue());
            }
        }

这个放在map里的key是否toLowerCase一下更合理

**Comment by hellokaton** [comment]
@itomcat666 我尝试一下这个操作，不过目前你可以直接通过 `header` 判断

**Comment by hellokaton** [comment]
@itomcat666 这个问题在新版本中应该不存在的，可以看 [这个](https://github.com/lets-blade/blade/blob/dev/src/main/java/com/blade/mvc/http/Request.java#L321) 代码。
