### ISSUE TITLE
通过注解添加的task在linux服务器上没有执行

### ISSUE THREAD

**Issue by Linindoo** [lets-blade/blade#323]
同一个class里面通过注解以及 cron表达式添加了两个定时任务，这个两个定时任务在本地开发环境运行都是ok的，但是部署到正式服务器上去时就出现了问题，系统启动时日志显示添加了对应的task，但是这两个task就是不执行，也没有任何错误日志打印。
于是我去掉一个任务，重新部署，发现一个任务是可以顺利执行的。
所以这个task是跟环境有关系吗？那需要怎样才能正确执行这两个任务呢？

抱大腿！

- linux CentOS 7.2 64位  1核1g
- maven
-JDK1.8 和 bladeMVC-2.0.14.RELEASE

**Comment by hellokaton** [comment]
@zhoriya 可以发一下你的 `cron` 表达式所在的类截图吗？

**Comment by Linindoo** [comment]
> @zhoriya 可以发一下你的 `cron` 表达式所在的类截图吗？
![qq 20190116091422](https://user-images.githubusercontent.com/26195410/51220173-238cb900-196f-11e9-9c1a-e8389a6dcefa.png)
就是这个

![qq 20190116133640](https://user-images.githubusercontent.com/26195410/51228505-d3741d80-1993-11e9-91aa-e3da8a88e073.png)
补充

**Comment by Linindoo** [comment]
![image](https://user-images.githubusercontent.com/26195410/51291134-1f30d080-1a41-11e9-8d4d-6e6e3fa661bb.png)
看了下源码，找到问题所在了，原因应该是初始线程池的数量问题，所以在配置文件中加上了这条
![image](https://user-images.githubusercontent.com/26195410/51291202-543d2300-1a41-11e9-9ae8-085a5ded54c4.png)
然后就可以快乐地运行了，不过我有个疑问，1核1g地服务器检测到的处理器数量是1，所以默认的初始化线程池数量应该是2，但是为啥没有执行呢
