### ISSUE TITLE
开发环境使用 ctx.address() 得到 "27.0.0.1" 问题

### ISSUE THREAD

**Issue by woaer** [lets-blade/blade#330]
**当我在开发环境使用 `RouteContext `  上下文的 `address()` 方法获取请求 ip 时，返回的结果被截断了。**

控制器如下：
```
    @GetRoute("/")
    public String index(RouteContext ctx) {
        log.info("address => {}", ctx.address());
        return "index.html";
    }
```
通过 `http://127.0.0.1:9000/` 访问，下边是调试的截图：

![image](https://user-images.githubusercontent.com/10717787/51894804-aee06280-23e3-11e9-9c28-ddf108328a9c.png)

**环境说明**

1. Windows 7
2. maven
3. JDK 1.8 and blade `2.0.12.RELEASE`

**预期行为**

没有测试正式环境获取访问 ip 的问题，不清楚是否符合预期。

**附加信息**

在这个 commit [415812d](https://github.com/lets-blade/blade/commit/415812de8b7edbab7bf5f28f615d5d11af5cb4b3#diff-77b0592c042fa3503e13241c94a19953L270) 中，增加了字符截取代码，不知是何作用？

**Comment by hellokaton** [comment]
这是一个 bug，在 https://github.com/lets-blade/blade/pull/337 中已修复，感谢你的反馈。
