### ISSUE TITLE
nginx 配置域名访问后，静态文件 js、css文件报404错误

### ISSUE THREAD

**Issue by GISering** [lets-blade/blade#334]
- blade-2.0.12-releae
- maven
- JDK 1.8

![](http://ww1.sinaimg.cn/large/cca5a724ly1g0n5r7tpu2j21d702q0sx.jpg)

1. nginx配置：
      location /pm {
            proxy_pass http://127.0.0.1:9003/pm/index;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X- 
                                        Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
        }

2. balde配置了 contextPath
   app.context-path=/pm
3. 用IP地址直接访问没问题

**Comment by hellokaton** [comment]
@GISering 尝试将 nginx 配置修改为

```nginx
location /pm {
    proxy_pass http://127.0.0.1:9003/pm;
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
    add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-
    Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
}
```

不过还是建议一个端口一个服务比较方便。

**Comment by GISering** [comment]
配置 contextPath后，前台  ajax 访问，url 没有添加 pm前缀，前端报错
![](http://ww1.sinaimg.cn/large/cca5a724ly1g0zu3g25qtj20zb018mx7.jpg)

![访问url](http://ww1.sinaimg.cn/large/cca5a724ly1g0zu3g2hxwj20eo05edfv.jpg)

手动添加 contextPath 前缀后
![](http://ww1.sinaimg.cn/large/cca5a724ly1g0zua5ciw2j20ep065mxb.jpg)

错误变成

![](http://ww1.sinaimg.cn/large/cca5a724ly1g0zub4wa7vj2105011aa5.jpg)

无论怎么改都不能正常 访问
```
www.gisclouder.com/pm/contract/list/1/10
```
