### ISSUE TITLE
Handles any requests that don't match the defined routes

### ISSUE THREAD

**Issue by ebottabi** [lets-blade/blade#335]
Hi there,

I am looking handling all/any request that isn't defined. something like this below.

<img width="617" alt="screenshot 2019-03-05 at 16 02 32" src="https://user-images.githubusercontent.com/351587/53814676-5828f400-3f60-11e9-904f-344c602df493.png">

**Comment by ydq** [comment]
As far as I know, Blade does not support wildcard routing, but you can do this.

~~~java
app.get("/:wildcard",(req,resp)->{
        resp.text("wildcard route");
})
~~~

Maybe it helps you

**Comment by hellokaton** [comment]
@ebottabi  You can try it

```java
Blade.of().before("/", ctx -> {
    // do something
}).start(TaskApplication.class, args);
```

**Comment by ebottabi** [comment]
Thanks @biezhi
