### ISSUE TITLE
AsynRequestHandler broken in 1.5.1

### ISSUE THREAD

**Issue by frodeaa** [lets-blade/blade#35]
The changes done to add abort request method removed the `asyncContext.complete();` call, see https://github.com/biezhi/blade/commit/d26e0b51948a46dff9e9eb46597e6371f415aa76#diff-7aa3ea01b06a20338721e6335ed5ed92

**Comment by hellokaton** [comment]
:joy: Why don't you commit PR? this bug fixes.
