### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by rdmclin2** [lets-blade/blade#36]
代码里的注解用英文写吧，有利于国际化。中文在不同的编码下有可能乱码

**Comment by hellokaton** [comment]
哪个注解是中文的

**Comment by rdmclin2** [comment]
我在看你blade-kit里的代码，里面多数都是中文注释

**Comment by hellokaton** [comment]
好的，这个需要慢慢修改了，以前blade-core也全是中文，任务排队呢。。。

**Comment by rdmclin2** [comment]
哈哈，还有看到你代码里面很大一块还没有测试，写了测试的还用的main，该用Junit啦

**Comment by hellokaton** [comment]
方法大家都知道，这么多的工程代码量很庞大的，我一个人做什么都得一点一点来呢 :0

**Comment by rdmclin2** [comment]
=。=第一次看你这个项目着实让我激动了一把，尼玛原来java也可以像Nodejs一样简洁地写后端！不管了，菜就菜吧，我先尝试帮你写写测试用例 :)

**Comment by hellokaton** [comment]
其实有人答应帮忙写TestCase的，但最近也没信儿了。。最终还是一个人在开发/(ㄒoㄒ)/~~

**Comment by wsdjeg** [comment]
太赞了，相见恨晚，等的就是这样的框架，不敢说能藏着写测试，我先熟悉下这个项目！

**Comment by hellokaton** [comment]
Welcome :smile:
