### ISSUE TITLE
似乎没有解决循环依赖的问题

### ISSUE THREAD

**Issue by xjt2016** [lets-blade/blade#362]
实现的IOC似乎没有处理循环依赖的问题吧，Spring有三级缓存进行处理

**Comment by chlch** [comment]
先把每个@Bean注解的类都实例化了，然后再填充有@Inject注入的字段，反正所有@Bean注解的类都实例化过了，填充字段时直接set就好了，一种简单便捷的方式。三级缓存主要是aop代理类的考虑吧，blade感觉用webhook扩展也够了。
