### ISSUE TITLE
blade和其他MVC框架的区别在哪里，比如springboot

### ISSUE THREAD

**Issue by llx1993** [lets-blade/blade#365]
Please provide the following information if applicable:

- Operating system and its version
- Build tools (e.g. maven or gradle)
- JDK version and blade version(e.g `2.0.8-R1`)

**Comment by leatomic** [comment]
针对老铁的问题斗胆回答一下：
1、操作系统是无关的，这是Java Web开发框架，最终打包出来的是一个Jar（运行在操作系统对应版本的JVM上），不要忘了Java“一处编写，到处运行”的特性！

2、构建工具都可以的，Maven、Gradle甚至从空项目开始也是可以的，只不过推荐Maven或者Gradle并且有相关的依赖直接引入

3、JDK1.8+ (项目是18年建的，最低1.8没毛病)，看README.md#Features
先看README.md！
先看README.md！
先看README.md！

和其他MVC框架的区别在哪里？我猜您想问的是：和例如Spring Web MVC、Spring WebFlux（尤其是）、Struts 2等的区别在哪吧？！（Spring Boot不是MVC框架）
其实你可以对比下：
  这个项目的README.md#Features vs 你在使用的MVC框架的特性
从不支持Servlet API，不需要部署在Servlet容器，这点来看拿Spring WebFlux来对比更有价值

从你的提问可以看出您可能基础比较差，建议先多多打好基础先，尤其是一些基本的概念理解不是很到位哈哈。
希望能帮到你:）
