### ISSUE TITLE
静态文件路径中存在空格 找不到文件

### ISSUE THREAD

**Issue by wind-hx** [lets-blade/blade#369]
![bug](https://user-images.githubusercontent.com/17685971/63852714-86493700-c9cb-11e9-875e-a85790bf3775.jpg)

代码中获取的文件路径 /Volumes/shaoshuai%20SSD/project/java-project/roo/target/classes/static/plugins/noty/noty.css

实际路径 /Volumes/shaoshuai SSD/project/java-project/roo/target/classes/static/plugins/noty/noty.css

**Comment by ghost** [comment]
@wind-hx 
该问题已经在 2.0.3 的版本中解决，建议升级到更高的版本

![image](https://user-images.githubusercontent.com/28976436/66697387-be9c9e80-ed07-11e9-8180-687423cb90cb.png)
