### ISSUE TITLE
GetRoute

### ISSUE THREAD

**Issue by Silentdoer** [lets-blade/blade#372]
能否做一个注解，使得GetRoute可以返回字符串而不是必须得是某个文件。

**Comment by Silentdoer** [comment]
> 能否做一个注解，使得GetRoute可以返回字符串而不是必须得是某个文件。

经过测试可以用@JSON注解，但是它Content-Type固定就是application/json;charset=utf-8的【ie是text/html】，但是我们这边需求有需要能够指定Content-Type的，这块能够加个注解？？

**Comment by ydq** [comment]
可以看看这里：https://lets-blade.com/docs/response.html
