### ISSUE TITLE
建议不要使用maven modules，可以用git的子模块！

### ISSUE THREAD

**Issue by wsdjeg** [lets-blade/blade#38]
将每一个模块分离出去

**Comment by wsdjeg** [comment]
@biezhi 
我看了目前这个项目的结构，各个模块之间并不是相互依赖的，而且有的模块中重复包含了另一个，为什么不将这些模块单独出去维护呢，另外目前我自己的开发环境对modules支持不太好 :smile:

**Comment by hellokaton** [comment]
目前的项目是一个标准的maven多模块结构，git子模块的方式我没有用过，当然你的提议我最初是那么做的，这样要建很多仓库喽。而且大部分项目都是这么干的，模块间的依赖都是以core为核心，你是什么IDE? idea吗

**Comment by wsdjeg** [comment]
> 而且大部分项目都是这么干的

大部分项目都不是用maven来管理模块的吧，基本上都是git或者svn来管理模块吧。我是vim配上插件。
https://github.com/wsdjeg/DotFiles
