### ISSUE TITLE
patchca调用render函数报500

### ISSUE THREAD

**Issue by tusiman** [lets-blade/blade#398]
public static void main(String[] args) {

        // 这行代码应该放在启动时加载
        DefaultPatchca patchca = new DefaultPatchca();

        Blade.of().get("/code", context -> {
            try {
                String code = patchca.render();
                System.out.println("verify code: " + code);
            } catch (PatchcaException e) {
                System.out.println("Patchca Error: " + e.getMessage());
            }
        }).get("/verify", context -> {
            String  code    = context.fromString("code", "CODE");
            boolean success = patchca.verify(code);
            context.text("verify result: " + success);
        }).start(VerifyCodeApplication.class, args);
    }

2020/02/27 08:57:30 ERROR [   worker@thread-1 ]       c.b.s.n.HttpServerHandler :  500          GET /code

**Comment by wuma2020** [comment]
DefaultPatchca 这个类和 PatchcaException 异常类的代码可以也放上来吗？ 还有这个是依赖于哪一个版本的，可以标注一下
