### ISSUE TITLE
使用enableCors配置跨域后，请求浏览器仍提示跨域

### ISSUE THREAD

**Issue by tusiman** [lets-blade/blade#399]
后端代码：

    public static void main(String[] args) {

        Blade.of()
            .enableCors(Boolean.TRUE) // or   .enableCors(Boolean.TRUE, getCorsConfiger())
            .start(CorsApplication.class, args);

    }

前端代码：

    $("#b01").click(function () {

        $.ajax({
            url : 'http://localhost:9000/users',
            type : "get",
            headers: {
                'webserver': 'blade'
            },
            success : function(data){
                console.log(data);
            }
        });
    });

浏览器console:

Access to XMLHttpRequest at 'http://localhost:9000/users' from origin 'http://localhost:63342' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET http://localhost:9000/users net::ERR_FAILED

**Comment by ebottabi** [comment]
@tusiman you can do this by implementing a class that extends **com.blade.mvc.hook.WebHook**  see image below
![image](https://user-images.githubusercontent.com/351587/77168734-a0a64780-6ab8-11ea-947e-76ab4907b691.png)

my security class handles auth and CORS needs and couple of other checks.

**Comment by psh686868** [comment]
请检查接口 http://localhost:9000/users  是不是调通， 在域名http://localhost:63342 下请求http://localhost:9000/users 时，浏览器发生预检查请求，通过服务返回的Access-Control-Allow-Origin header头信息来判断是否进行跨域请求，所以当http://localhost:9000/users 当网络接口不通时，浏览器无法通过预检来进行是否跨越请求，导致blocked by CORS policy
