### ISSUE TITLE
CorsMiddleware don’t use the CorsConfigurer

### ISSUE THREAD

**Issue by nguereza-tony** [lets-blade/blade#418]
### Is your feature request related to a problem? Please describe.**
In the class CorsMiddleware the overwrite method « handle() » use the default values of cors policies instead of the CorsConfigurer.

### Describe the solution you'd like
Change method to :

@Override
    public void handle(RouteContext context) {
this. allowHeads(context)
      . allowMethods(context)
      . allowCredentials(context)
      . setMaxAge(context);
context.status(204);
}

**Comment by hellokaton** [comment]
Make CORS configuration easy in `2.1.x` version, as shown in the following code.

```java
CorsOptions corsOptions = CorsOptions.forAnyOrigin().allowNullOrigin().allowCredentials();
Blade.of()
     .cors(corsOptions)
     .listen().start(Application.class);
```
