### ISSUE TITLE
Consuming Third party Rest resource

### ISSUE THREAD

**Issue by Patrick5455** [lets-blade/blade#419]
Please provide the following information if applicable:

- Operating system and its version: Ubuntu Version 20
- Build tools: Maven
- JDK version and blade version: JDK 8, latest blade version

How can I consume a rest endpoint from a third party in blade just the way Spriingbbit provides RestTemplate and WebClient for such.

Thanks.

**Comment by VasilisAndritsoudis** [comment]
Hello I would like to give it a try. However I will need some more information.

**Comment by Patrick5455** [comment]
please what  more info do you need me to supply?

**Comment by VasilisAndritsoudis** [comment]
As far as I know (meaning work I have done which is in Java Spring Boot), when you "consume" an endpoint in java you make a request to it, with the relevant code, and then you have the option to save the JSON response (this is what I assume it is), using the equivalent classes. This means you have a class structure of the endpoint's response. So what I would like to know is what you want to do with the response, and whether the response is JSON.

**Comment by Patrick5455** [comment]
Hey Chief, have you used Blade to consume a restAPi before, if you have, how did you go about it? . I think the question is quite clear. Thanks

**Comment by VasilisAndritsoudis** [comment]
Okay, sorry I got it wrong, my bad.

**Comment by Patrick5455** [comment]
I am closing this issue as I have decided to use the native java .net package or .ws package.
