### ISSUE TITLE
blade-1.6.0新特性

### ISSUE THREAD

**Issue by hellokaton** [lets-blade/blade#53]
1. 更简化的配置(提供默认配置)
2. 支持非web应用开发
3. 优化代码
4. 重构数据库操作
5. 内置数据库连接池
6. 更灵活的路由操作
7. 重新修订官网文档
8. 暂时去除servlet3x异步
9. 去除多余繁杂的配置，追求精简实用
10. 提供易扩展的IOC，路由接口

**Comment by builds2014** [comment]
1.6 版本上传到 maven 中心库了吗？   这里下载的https://github.com/blade-samples/sample 的 例子 1.6.0-alpha  依赖更新失败。

**Comment by harley-byte** [comment]
是的。1.6 load不下来

**Comment by hellokaton** [comment]
@builds2014 @fleaLi 还没释放出来。我今天提交一个版本。
