### ISSUE TITLE
Blade plugin API broken

### ISSUE THREAD

**Issue by frodeaa** [lets-blade/blade#61]
The change in ebdb2e1fb7881baf8ca3b80f6f8f4b27b9c5056b broke how plugins can be used

```
Sql2oPlugin sql2oPlugin = blade.plugin(Sql2oPlugin.class);
sql2oPlugin.config(url, user, pass).run();
```

[sql2o](http://bladejava.com/docs/modules/sql2o)

**Comment by hellokaton** [comment]
I'm sorry, at present the blade-sql2o has been abandoned, can have a try if you want to operate database [blade-jdbc](https://github.com/bladejava/blade-jdbc) :smile:  

Have what problem can leave a message, thank you for your support.
