### ISSUE TITLE
Class hot loader

### ISSUE THREAD

**Issue by hellokaton** [lets-blade/blade#85]
Automatically load the modified class file.

**Comment by wangxian** [comment]
@biezhi 如果使用？

**Comment by eddie-wang** [comment]
每次request来的时候 看一下有没有文件变化 然后把旧的class 从classloader中移出来,替换成新的. 只在debug模式开启这个功能。 我想试试解决这个issue

**Comment by eddie-wang** [comment]
This might help. https://github.com/HotswapProjects/HotswapAgent

**Comment by hellokaton** [comment]
我认为可行的做法应该是开启一个线程定时监控源码是否有修改，源码的修改分为:

- Java代码修改
- 配置修改（暂时可忽略）
- 模板、静态资源修改

当 `Java` 源文件发生变动的时候重新 **编译**（或者叫重置ClassLoader?）。

**Comment by eddie-wang** [comment]
嗯嗯 可以的 我来试试能不能行 你可以把这个assign给我 正好最近公司事情不多 我研究下这个

**Comment by eddie-wang** [comment]
刚做了些研究，现在的想法是：
1. 对于 java代码修改：
   检测源代码文件的变化
   动态重新编译代码
  重新加载class， 这步需要自定义一个新的classloader， 因为 jvm默认的classloader会首先监测需要被加载的class有没有在list中，如果有的话就不会加载。

2. 对于模板、静态资源修改
   首先看有没有文件变化，有的话就copy到对应的目录

**Comment by dongm2ez** [comment]
in vert.x he has `io.vertx.core.Launcher` class, this class is can reference.

[API](http://vertx.io/docs/apidocs/io/vertx/core/Launcher.html)

gradle config
```
run {
    args = ['run', 'com.example.web.MainVerticle',
            "--launcher-class=io.vertx.core.Launcher",
            "--redeploy=src/**/*.*",
            "--on-redeploy=./gradlew classes"
    ]
}
```
 [demo](https://github.com/vert-x3/vertx-examples/tree/master/gradle-redeploy)

**Comment by eddie-wang** [comment]
Hot load for static and template files are done. Pushed to my remote branch.  Now i am blocked by how to replace the new compiled class file with old ones in classLoader. It seems there is no easy way to do that in jvm. Will research more and update here once i find something.

**Comment by greenlaw110** [comment]
@eddie-wang there is no way to replace classes in a ClassLoader, what you can do is to replace the class loader with an new instance. 

[ActFramework](https://github.com/actframework/actframework/) has fully support to dev mode hot reloading. You can refer to 

* https://github.com/actframework/actframework/blob/master/src/main/java/act/app/App.java#L426
* https://github.com/actframework/actframework/blob/master/src/main/java/act/app/DevModeClassLoader.java
