### ISSUE TITLE
初学者请教一个小问题

### ISSUE THREAD

**Issue by kran** [lets-blade/blade#87]
初学JAVA，对Servlet不很了解，在看blade源码的时候有一个疑问，举例如下：
Blade.routers返回Routers对象，Routers.addRoute会把route放进一个HashMap
如果在控制器里调用这个函数，是否会造成线程安全上的问题？

我知道问题跟blade没什么关系，也不会有人这样用。。。。只是真的很想知道这样用会不会出问题？

多谢啦。 ：）

**Comment by hellokaton** [comment]
非常好的一个问题，是有这个问题的，从 [代码](https://github.com/biezhi/blade/blob/master/blade-core/src/main/java/com/blade/mvc/route/Routers.java#L48) 这里可以看到，这个容器是一个 `HashMap` ，应该修正为 `ConcurrentHashMap`。已经修复 😄 thx

**Comment by kran** [comment]
这速度太快了！
没想到真是个问题，我继续看源码去了。：D

**Comment by hellokaton** [comment]
@kran 因为创建的是 `HashMap`，它不是线程安全的容器，在使用的时候就会出现并发问题。

**Comment by kran** [comment]
@biezhi 一般来说路由只初始化一次吧？我说的那种使用情况应该不会出现。
Blade的filters,servlets都是HashMap，或者其它能够间接获取到的对象比如ioc，都应该保护起来吗？还是各有取舍？

**Comment by hellokaton** [comment]
@kran 是的，路由和ioc容器这些在框架启动的时候初始化，用的时候基本都是读取操作。
之前设计的时候没有考虑并发的问题，也没有出现过，不过在代码上必须要处理的。

**Comment by kran** [comment]
@biezhi 明白了，多谢。
