### ISSUE TITLE
Perfect document

### ISSUE THREAD

**Issue by hellokaton** [lets-blade/blade#91]
完善现有文档。

**Comment by wangxian** [comment]
此项目很棒，期待更好的发展。

如果
1. 完善的文档
2. 期望提供一下示例项目源码

非常棒了

感谢作者的辛苦工作；

**Comment by hellokaton** [comment]
@wangxian 文档和示例都有了，还会继续完善。

- https://lets-blade.com/zh-cn/docs/
- https://github.com/lets-blade/awesome-blade
