### ISSUE TITLE
set Timeout has no effect！

### ISSUE THREAD

**Issue by hwsungsoft** [lets-blade/blade#99]
代码如下：
         
-         HttpRequest request = HttpRequest.post(url)
- 				.header(Header.HEADER_CONTENT_TYPE, Constant.Browser.Content_Type)
- 				.header(Header.HEADER_COOKIE, this.cookie)
- 				.send(body.toString());
-         String res = request.connectTimeout(5000).readTimeout(5000).body();
-         request.disconnect();

设置了超时，当没有返回的时候，就会一直阻塞导致线程挂起。
令我困惑的是，为什么timeout不起作用呢？

**Comment by hellokaton** [comment]
Blade内置的Http请求工具类已移除，可以尝试 [这里](https://github.com/biezhi/oh-my-request)
